import { describe, it, expect } from 'vitest';
import {
  emitClaims,
  emitFileManifestClaims,
  isFileLevelClaim,
  columnIndexOf,
  columnPredicate,
  FILE_LEVEL_ORDINAL,
  SUBJECT_PREDICATE,
  IGNORED_PREDICATE,
  LISTED_PREDICATE,
  type SourceObservationSet,
} from './claim.ts';
import { projectNormalised } from './project-normalised.ts';
import { checkNoInflationClaims } from '../ci/trust-rating.ts';

// Test names follow the project's Subject_Scenario_Outcome convention.
//
// The file-level-claim convention (issue #434, ADR 0016) attests the verbatim
// as-published structure the per-row claim stream omits - the header set/order/
// exact strings, the subject column, and the curated furniture - on a sentinel
// ordinal so it is unambiguously NOT an observation. These tests fix the
// convention's guarantees: exact preservation, and non-pollution of the
// observation multiset / row-count / existence invariants when the two claim
// streams mix.

// A source whose header exercises the hazards E1 exists to preserve: a wholly-
// empty column (populated on no row), a truncated header (the real
// 'Licence Issued Dat'), and interior whitespace. The subject column sits in the
// MIDDLE, not first, so subject placement is genuinely tested.
function awkwardSource(): SourceObservationSet {
  return {
    sourceFile: 'synthetic/awkward.csv',
    vintage: '2026-01-01',
    columns: ['Status', 'Call Sign', 'Licence Issued Dat', 'Notes  Column', 'AlwaysEmpty'],
    subjectColumn: 'Call Sign',
    headerLine: 1,
    ignoredLines: [
      { line: 5, content: 'Generated By:  A Person  01/01/2026,,,,' },
      { line: 6, content: 'Ofcom,,,,' },
    ],
    encoding: 'utf8',
    rows: [
      { 'Status': 'Allocated', 'Call Sign': 'M7TEE', 'Licence Issued Dat': '01/02/2020', 'Notes  Column': '', 'AlwaysEmpty': '' },
      { 'Status': 'Reserved', 'Call Sign': 'G0ABC', 'Licence Issued Dat': '', 'Notes  Column': 'seen twice', 'AlwaysEmpty': '' },
    ],
  };
}

describe('the file-level manifest attests the verbatim as-published structure', { tags: ['unit'] }, () => {
  it('FileManifest_WhenEmitted_AttestsEveryColumnVerbatimInSourceOrder', () => {
    const source = awkwardSource();
    const manifest = emitFileManifestClaims(source);
    for (let index = 0; index < source.columns.length; index += 1) {
      const claim = manifest.find(c => c.predicate === columnPredicate(index));
      expect(claim, `@column/${index} present`).toBeDefined();
      // The object is the EXACT header string - truncation, interior whitespace,
      // and a column empty on every row all preserved.
      expect(claim?.object).toBe(source.columns[index]);
    }
    // The wholly-empty column - which would VANISH from the per-row claims (it
    // has no non-empty cell) - is still attested here.
    expect(manifest.some(c => c.object === 'AlwaysEmpty')).toBe(true);
  });

  it('SubjectColumn_WhenEmitted_IsNamedByItsVerbatimHeaderRegardlessOfPosition', () => {
    const manifest = emitFileManifestClaims(awkwardSource());
    const subject = manifest.find(c => c.predicate === SUBJECT_PREDICATE);
    expect(subject?.object).toBe('Call Sign');
  });

  it('CuratedFurniture_WhenEmitted_RidesFileLevelOrdinalCarryingItsSourceLine', () => {
    const manifest = emitFileManifestClaims(awkwardSource());
    const ignored = manifest.filter(c => c.predicate === IGNORED_PREDICATE);
    expect(ignored.map(c => c.object)).toEqual(['Generated By:  A Person  01/01/2026,,,,', 'Ofcom,,,,']);
    expect(ignored.map(c => c.provenance.position)).toEqual([
      { kind: 'csv-line', line: 5 },
      { kind: 'csv-line', line: 6 },
    ]);
  });

  it('EveryFileLevelClaim_WhenEmitted_IsRawAsPublishedOnTheSentinelOrdinal', () => {
    const manifest = emitFileManifestClaims(awkwardSource());
    expect(manifest.length).toBeGreaterThan(0);
    for (const claim of manifest) {
      expect(claim.layer).toBe('raw');
      expect(claim.rule).toBeUndefined();
      expect(claim.provenance.ordinal).toBe(FILE_LEVEL_ORDINAL);
      expect(isFileLevelClaim(claim)).toBe(true);
    }
  });

  it('ColumnIndexOf_WhenGivenAnyPredicate_DecodesOnlyRealColumnPredicates', () => {
    expect(columnIndexOf(columnPredicate(0))).toBe(0);
    expect(columnIndexOf(columnPredicate(12))).toBe(12);
    expect(columnIndexOf(SUBJECT_PREDICATE)).toBeUndefined();
    expect(columnIndexOf(LISTED_PREDICATE)).toBeUndefined();
    expect(columnIndexOf('@column/notanumber')).toBeUndefined();
  });
});

describe('file-level claims never pollute the observation folds', { tags: ['unit'] }, () => {
  it('ObservationClaims_WhenEmitted_NeverCarryTheFileLevelSentinel', () => {
    // The per-row emit and the file-level emit are disjoint by ordinal: no
    // observation is ever mistaken for file-level, so the existence fold's
    // 0..n-1 range and the manifest's sentinel can never collide.
    const claims = emitClaims(awkwardSource());
    expect(claims.every(c => c.provenance.ordinal >= 0)).toBe(true);
    expect(claims.some(isFileLevelClaim)).toBe(false);
  });

  it('MixedClaimStream_WhenReprojected_YieldsExactlyTheObservationRows', () => {
    // The load-bearing non-pollution check: concatenate the manifest with the
    // per-row claims and reproject. The record set must be EXACTLY the source
    // rows - same count, same values - the file-level claims contributing no
    // phantom record at the sentinel ordinal.
    const source = awkwardSource();
    const mixed = [...emitClaims(source), ...emitFileManifestClaims(source)];
    const projected = projectNormalised(mixed, source.columns, source.subjectColumn);
    expect(projected.length).toBe(source.rows.length);
    for (let i = 0; i < source.rows.length; i += 1) {
      for (const column of source.columns) {
        expect(projected[i].values[column]).toBe(source.rows[i][column] ?? '');
      }
    }
    // No record was created at the sentinel ordinal.
    expect(projected.some(record => record.ordinal < 0)).toBe(false);
  });

  it('MixedClaimStream_WhenCheckedForInflation_RaisesNoViolation', () => {
    // The manifest claims are raw / no-rule / As-published, so the #404
    // no-inflation invariant is untouched when they join the stream.
    const source = awkwardSource();
    const mixed = [...emitClaims(source), ...emitFileManifestClaims(source)];
    expect(checkNoInflationClaims(mixed)).toEqual([]);
  });
});
