name: Fetch and Commit CSV File

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write # Grants write access to the repository contents

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch CSV file and output file size
      shell: pwsh
      run: |
        Write-Host "Fetching CSV file from URL..."
        Invoke-WebRequest -Uri "https://www.ofcom.org.uk/siteassets/resources/documents/manage-your-licence/amateur/amateur-callsigns.csv" -OutFile "amateur-callsigns.csv"
        Write-Host "File downloaded. Checking file size..."
        $file = Get-Item "amateur-callsigns.csv"
        if ($file.Length -eq 0) {
          Write-Error "Error: The downloaded file is empty!"
          exit 1
        }
        Write-Host "File size is valid. File size: $($file.Length) bytes."
        Write-Host "Directory listing:"
        Get-ChildItem -Path .

    - name: Commit and push changes
      shell: pwsh
      run: |
        Write-Host "Configuring Git user..."
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        Write-Host "Adding file to Git..."
        git add amateur-callsigns.csv
        Write-Host "Committing changes..."
        git commit -m "Update amateur callsigns CSV file"
        Write-Host "Pushing changes to repository..."
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
